import { defineConfig } from "tsup";

const shared = {
  format: ["cjs", "esm"] as const,
  splitting: false,
  sourcemap: true,
  treeshake: true,
  outDir: "dist",
  external: [
    "@prisma/client",
    "@effect/sql-sqlite-node",
    "react",
    "react-dom",
  ],
};

export default defineConfig([
  {
    ...shared,
    entry: {
      index: "src/index.ts",
      Process: "src/Process.ts",
      ProcessScope: "src/ProcessScope.ts",
      ProcessLifecycleScope: "src/ProcessLifecycleScope.ts",
      ProcessGroupScope: "src/ProcessGroupScope.ts",
      QueueResource: "src/QueueResource.ts",
      ProcessGroup: "src/ProcessGroup.ts",
      ProcessStore: "src/ProcessStore.ts",
      ProcessStorage: "src/ProcessStorage.ts",
      "store/QueueResource": "src/store/queueResource.ts",
      "store/Log": "src/store/log.ts",
      "store/RunResource": "src/store/RunResource.ts",
      "store/ProcessLifecycle": "src/store/processLifecycle.ts",
      "store/ProcessGroup": "src/store/processGroup.ts",
      "store/ProcessExecution": "src/store/processExecution.ts",
      Query: "src/Query.ts",
      ResourceConfigure: "src/ResourceConfigure.ts",
      RuntimeStorage: "src/RuntimeStorage.ts",
      State: "src/State.ts",
      RunResourceScope: "src/RunResourceScope.ts",
      CommandAuth: "src/CommandAuth.ts",
      ControlProtocol: "src/ControlProtocol.ts",
      ControlTransportRpc: "src/ControlTransportRpc.ts",
      storeTransport: "src/storeTransport.ts",
      logTransport: "src/logTransport.ts",
      controlTransport: "src/controlTransport.ts",
      terminalTransport: "src/terminalTransport.ts",
      StoreMessage: "src/StoreMessage.ts",
      TelemetryHub: "src/TelemetryHub.ts",
      RunResourceProjection: "src/RunResourceProjection.ts",
      ArchiveSink: "src/ArchiveSink.ts",
      "sink/ArchiveSink": "src/sink/ArchiveSink.ts",
      ProjectionSink: "src/ProjectionSink.ts",
      "sink/ProjectionSink": "src/sink/ProjectionSink.ts",
      BroadcastSink: "src/BroadcastSink.ts",
      "sink/BroadcastSink": "src/sink/BroadcastSink.ts",
      telemetryTransport: "src/telemetryTransport.ts",
      Terminal: "src/Terminal.ts",
      TerminalRpc: "src/TerminalRpc.ts",
      LogTransportRpc: "src/LogTransportRpc.ts",
      ProcessManager: "src/ProcessManager.ts",
      ControlService: "src/ControlService.ts",
      Logs: "src/Logs.ts",
      "storage/sqlite": "src/storage/sqlite/index.ts",
      "storage/redis": "src/storage/redis/index.ts",
      "storage/prisma": "src/storage/prisma.ts",
      "prisma/index": "src/prisma/index.ts",
      "bin/effect-pm": "src/bin/effect-pm.ts",
      "ops-ui/index": "src/ops-ui/index.ts",
      "react/index": "src/react/index.ts",
      "react/adapters/fetch": "src/react/adapters/fetch.ts",
      "react/adapters/trpc": "src/react/adapters/trpc.ts",
    },
    dts: true,
    clean: true,
    esbuildOptions(options) {
      options.jsx = "automatic";
    },
  },
  {
    ...shared,
    entry: {
      "bin/effect-pm-group-child": "src/bin/effect-pm-group-child.ts",
    },
    dts: false,
    clean: false,
  },
]);
