/**
 * Prisma schema fragment for {@link PrismaProcessStore}.
 *
 * @remarks
 * This is the canonical schema published by `effect-pm`. The
 * {@link PrismaProcessStore} adapter assumes a model named `EffectPmEvent`
 * with these columns and indexes. Users obtain it either via:
 *
 * - the {@link prismaSchema} export (this constant), or
 * - the admin CLI: `npx effect-pm prisma:print-schema`, or
 * - the schema rewriter: `npx effect-pm add prisma`.
 *
 * The model uses the envelope-first design of `ProcessStore`:
 * - top-level columns are the dimensions we routinely filter / sort on
 *   (`type`, `entityType`, `entityId`, `occurredAt`),
 * - `payload` carries event-type-specific data as JSON,
 * - `attributes` is reserved for free-form structured metadata.
 *
 * Adding new event types never requires a schema migration: the envelope
 * stays the same, only the shape inside `payload` evolves.
 *
 * @public
 */
export const prismaSchema = `// ─── effect-pm: ProcessStore (single-table envelope) ─────────────────────────
// Generated by 'effect-pm add prisma'. Safe to edit indexes; do not rename
// the model or its core columns — the PrismaProcessStore adapter depends on
// this exact shape.

model EffectPmEvent {
  id          String   @id
  type        String
  occurredAt  DateTime
  entityType  String
  entityId    String
  attributes  Json?
  payload     Json
  createdAt   DateTime @default(now())

  @@index([entityType, entityId, type, occurredAt])
  @@index([type, occurredAt])
  @@index([entityType, entityId, occurredAt])
}
`;

/**
 * Marker used by the admin CLI to detect whether the effect-pm models have
 * already been added to a Prisma schema. Idempotency for
 * `npx effect-pm add prisma` is based on this exact substring.
 *
 * @public
 */
export const prismaSchemaModelMarker = "model EffectPmEvent {";
