/**
 * Prisma schema fragment for {@link PrismaRuntimeStorage}.
 *
 * @remarks
 * This is the canonical schema published by effect-pm for the Prisma
 * `RuntimeStorage` adapter. Consumers own the Prisma schema, migrations, and
 * generated client; effect-pm only documents the structural delegate shape it
 * calls at runtime.
 *
 * The Prisma model is named `EffectPmRuntimeRecord`, so generated clients expose
 * `client.effectPmRuntimeRecord`. The physical database table is mapped to
 * `effect_pm_runtime_records`, matching the SQLite adapter's table name.
 * Runtime JSON blobs are serialized into string columns (`*_json`) to keep
 * null / unset semantics independent of Prisma's generated JSON null sentinel
 * types.
 *
 * @public
 */
export const prismaSchema = `// ─── effect-pm: RuntimeStorage (normalized runtime records) ─────────────────
// Generated by 'effect-pm add prisma'. Consumers own migrations and may add
// provider-specific indexes, but do not rename the model, mapped table, or core
// columns — the PrismaRuntimeStorage adapter depends on this structural shape.

model EffectPmRuntimeRecord {
  id          String   @id
  type        String
  occurredAt  DateTime
  createdAt   DateTime
  runId       String
  processType String
  processId   String
  subjectType String?
  subjectId   String?
  key         String?
  indexA      String?
  indexB      String?
  indexC      String?
  indexD      String?
  indexE      String?
  indexF      String?
  indexG      String?
  indexH      String?
  indexNamesJson String?  @map("index_names_json")
  payloadJson    String?  @map("payload_json")
  attributesJson String?  @map("attributes_json")
  readonly    Boolean?

  @@index([runId])
  @@index([type, occurredAt])
  @@index([processType, processId, occurredAt])
  @@index([subjectType, subjectId, occurredAt])
  @@index([key])
  @@index([occurredAt])
  @@index([createdAt])
  @@index([indexA])
  @@index([indexB])
  @@index([indexC])
  @@index([indexD])
  @@index([indexE])
  @@index([indexF])
  @@index([indexG])
  @@index([indexH])
  @@map("effect_pm_runtime_records")
}
`;

/**
 * Marker used by the admin CLI to detect whether the effect-pm model has
 * already been added to a Prisma schema.
 *
 * @public
 */
export const prismaSchemaModelMarker = "model EffectPmRuntimeRecord {";
