// The full API-reference model — generated by scripts/gen-api.ts (`pnpm docs:api`) into api.json.
// Used by the per-namespace and per-symbol pages. The /api landing page uses ./api-index (a tiny
// summary) instead, so it never pulls the whole model.

import { slugForEntry } from "./api-index.js";

// Load as a RAW string, not a JSON module — importing a 679 KB .json makes Vite generate a 3 MB
// base64 `sourcesContent` map for it on every compile, which crawled the dev server.
const rawModel = import.meta.glob<string>("../../api-model.json", {
  query: "?raw",
  import: "default",
  eager: true,
});

export { slugForEntry };

export interface ApiTag {
  readonly name: string;
  readonly text: string;
}
export interface ApiSource {
  readonly file: string;
  readonly line: number;
}
export interface ApiSymbol {
  readonly entry: string;
  readonly name: string;
  readonly qualifiedName: string;
  readonly url: string;
  readonly kind: string;
  readonly signatures: ReadonlyArray<string>;
  readonly typeText?: string;
  readonly sourceText: string;
  readonly summary: string;
  readonly rawComment: string;
  readonly tags: ReadonlyArray<ApiTag>;
  readonly category?: string;
  readonly linkTargets: ReadonlyArray<string>;
  readonly source: ApiSource;
}
export interface ApiNamespace {
  readonly entry: string;
  readonly symbols: ReadonlyArray<ApiSymbol>;
}

const model: { readonly repoBaseUrl?: string; readonly entries: ReadonlyArray<ApiNamespace> } =
  JSON.parse(Object.values(rawModel)[0] ?? '{"entries":[]}');

export const namespaces = (): ReadonlyArray<ApiNamespace> => model.entries;

// GitHub blob base (…/blob/REF) for "view source" links; "" when the model has no remote.
export const repoBaseUrl = (): string => model.repoBaseUrl ?? "";

/** GitHub URL for a symbol's source line, or undefined when no repo base is known. */
export const sourceUrl = (file: string, line: number): string | undefined =>
  model.repoBaseUrl ? `${model.repoBaseUrl}/${file}#L${line}` : undefined;

export const namespaceBySlug = (slug: string): ApiNamespace | undefined =>
  model.entries.find((e) => slugForEntry(e.entry) === slug);

export interface FoundSymbol {
  readonly ns: ApiNamespace;
  readonly symbol: ApiSymbol;
}
export const findSymbol = (nsSlug: string, name: string): FoundSymbol | undefined => {
  const ns = namespaceBySlug(nsSlug);
  const symbol = ns?.symbols.find((s) => s.name === name);
  return ns !== undefined && symbol !== undefined ? { ns, symbol } : undefined;
};

// Every [namespace, symbol] pair — the static paths for the per-symbol routes.
export const allSymbolPaths = (): ReadonlyArray<readonly [string, string]> =>
  model.entries.flatMap((e) =>
    e.symbols.map((s): readonly [string, string] => [slugForEntry(e.entry), s.name]),
  );
