// The API-reference model — generated by scripts/gen-api.ts (`pnpm docs:api`) into api.json and
// imported here as the site's data source. Grouped by namespace; each symbol carries its qualified
// name, checker-resolved signatures, and raw doc comment for rendering. api.json is committed, so the
// site builds without running the extractor.

import apiJson from "../../api.json";

export interface ApiTag {
  readonly name: string;
  readonly text: string;
}
export interface ApiSource {
  readonly file: string;
  readonly line: number;
}
export interface ApiSymbol {
  readonly entry: string;
  readonly name: string;
  readonly qualifiedName: string;
  readonly url: string;
  readonly kind: string;
  readonly signatures: ReadonlyArray<string>;
  readonly typeText?: string;
  readonly summary: string;
  readonly rawComment: string;
  readonly tags: ReadonlyArray<ApiTag>;
  readonly category?: string;
  readonly linkTargets: ReadonlyArray<string>;
  readonly source: ApiSource;
}
export interface ApiNamespace {
  readonly entry: string;
  readonly symbols: ReadonlyArray<ApiSymbol>;
}

const model: { readonly entries: ReadonlyArray<ApiNamespace> } = apiJson;

// A namespace name → URL slug: "(top-level)" reads cleaner as "top-level", and "storage/sqlite"
// can't carry a slash in a single route segment.
export const slugForEntry = (entry: string): string =>
  entry === "(top-level)" ? "top-level" : entry.replace(/\//g, "-");

export const namespaces = (): ReadonlyArray<ApiNamespace> => model.entries;

export const namespaceBySlug = (slug: string): ApiNamespace | undefined =>
  model.entries.find((e) => slugForEntry(e.entry) === slug);

export interface FoundSymbol {
  readonly ns: ApiNamespace;
  readonly symbol: ApiSymbol;
}
export const findSymbol = (nsSlug: string, name: string): FoundSymbol | undefined => {
  const ns = namespaceBySlug(nsSlug);
  const symbol = ns?.symbols.find((s) => s.name === name);
  return ns !== undefined && symbol !== undefined ? { ns, symbol } : undefined;
};

// Every [namespace, symbol] pair — the static paths for the per-symbol routes.
export const allSymbolPaths = (): ReadonlyArray<readonly [string, string]> =>
  model.entries.flatMap((e) => e.symbols.map((s): readonly [string, string] => [slugForEntry(e.entry), s.name]));
