/**
 * File-router path table — walk `pages/**`, map disk `[param]` → Route `:param`,
 * emit typed `paths.gen.ts` for UrlBuilder / fileSystem.
 *
 * Used by the Vite plugin (watch) and `hyp` `--check` (CI).
 */
import * as NodeFs from "node:fs";
import * as NodePath from "node:path";

const EXT = /\.(tsx|ts|jsx|js)$/;

export type FileEntry = {
  readonly id: string;
  readonly filePath: string;
  readonly routePath: string;
  /** Absolute source file (for loaders). */
  readonly absFile: string;
};

export type EmitOptions = {
  readonly pagesDir: string;
  readonly outFile: string;
};

const walkFiles = (abs: string): ReadonlyArray<string> => {
  const out: Array<string> = [];
  for (const ent of NodeFs.readdirSync(abs, { withFileTypes: true })) {
    if (ent.name.startsWith(".") || ent.name.startsWith("_")) continue;
    const next = NodePath.join(abs, ent.name);
    if (ent.isDirectory()) out.push(...walkFiles(next));
    else if (EXT.test(ent.name)) out.push(next);
  }
  return out;
};

/** `[chapter].tsx` under docs → `/docs/[chapter]` */
export const toFilePath = (pagesDir: string, absFile: string): string => {
  const rel = NodePath.relative(pagesDir, absFile).replace(/\\/g, "/");
  const noExt = rel.replace(EXT, "");
  const segs = noExt.split("/").filter((s) => s.length > 0);
  if (segs[segs.length - 1] === "index") segs.pop();
  return "/" + segs.join("/");
};

/** `/docs/[chapter]` → `/docs/:chapter` */
export const toRoutePath = (filePath: string): string =>
  filePath.replace(/\[(\w+)\?\]/g, ":$1?").replace(/\[(\w+)\]/g, ":$1");

/** `/docs/[chapter]` → `docs_chapter` */
export const toRouteId = (filePath: string): string => {
  if (filePath === "/") return "index";
  return filePath
    .slice(1)
    .replace(/\[(\w+)\??\]/g, "$1")
    .replace(/\//g, "_");
};

/** Discover destination files under a pages directory. */
export const discover = (pagesDir: string): ReadonlyArray<FileEntry> => {
  const root = NodePath.resolve(pagesDir);
  if (!NodeFs.existsSync(root)) return [];
  const seen = new Set<string>();
  const entries: Array<FileEntry> = [];
  for (const absFile of walkFiles(root)) {
    const filePath = toFilePath(root, absFile);
    if (seen.has(filePath)) continue;
    seen.add(filePath);
    entries.push({
      id: toRouteId(filePath),
      filePath,
      routePath: toRoutePath(filePath),
      absFile,
    });
  }
  return entries.sort((a, b) => a.filePath.localeCompare(b.filePath));
};

/** Source text for `paths.gen.ts`. */
export const formatPathsModule = (
  entries: ReadonlyArray<FileEntry>,
): string => {
  const filePathUnion =
    entries.length === 0
      ? "never"
      : entries.map((e) => JSON.stringify(e.filePath)).join(" | ");
  const routePathUnion =
    entries.length === 0
      ? "never"
      : entries.map((e) => JSON.stringify(e.routePath)).join(" | ");
  const idUnion =
    entries.length === 0
      ? "never"
      : entries.map((e) => JSON.stringify(e.id)).join(" | ");

  const publicEntries = entries.map(({ id, filePath, routePath }) => ({
    id,
    filePath,
    routePath,
  }));

  return `/**
 * GENERATED by hyperlink-ts file router — do not edit.
 */
export const fileEntries = ${JSON.stringify(publicEntries, null, 2)} as const;

export const filePaths = [
${entries.map((e) => `  ${JSON.stringify(e.filePath)},`).join("\n")}
] as const;

export const routePaths = [
${entries.map((e) => `  ${JSON.stringify(e.routePath)},`).join("\n")}
] as const;

export type FilePath = ${filePathUnion};
export type RoutePath = ${routePathUnion};
export type FileRouteId = ${idUnion};
export type FileEntry = (typeof fileEntries)[number];
`;
};

/** Atomic write (temp + rename). */
export const writeAtomic = (outFile: string, body: string): void => {
  const abs = NodePath.resolve(outFile);
  NodeFs.mkdirSync(NodePath.dirname(abs), { recursive: true });
  const tmp = `${abs}.tmp`;
  NodeFs.writeFileSync(tmp, body, "utf8");
  NodeFs.renameSync(tmp, abs);
};

/**
 * Discover + emit. Returns whether the file content changed.
 */
export const emitPaths = (
  options: EmitOptions,
): { readonly changed: boolean; readonly entries: ReadonlyArray<FileEntry> } => {
  const entries = discover(options.pagesDir);
  const body = formatPathsModule(entries);
  const abs = NodePath.resolve(options.outFile);
  const prev = NodeFs.existsSync(abs)
    ? NodeFs.readFileSync(abs, "utf8")
    : undefined;
  if (prev === body) {
    return { changed: false, entries };
  }
  writeAtomic(abs, body);
  return { changed: true, entries };
};

/**
 * CI / hyp check — fail if emit would change the file.
 */
export const checkPaths = (options: EmitOptions): void => {
  const entries = discover(options.pagesDir);
  const body = formatPathsModule(entries);
  const abs = NodePath.resolve(options.outFile);
  if (!NodeFs.existsSync(abs)) {
    throw new Error(
      `file-router paths missing: ${abs} (run dev/build or hyp file-router emit)`,
    );
  }
  const prev = NodeFs.readFileSync(abs, "utf8");
  if (prev !== body) {
    throw new Error(
      `file-router paths stale: ${abs} — regenerate (Vite plugin / hyp file-router emit)`,
    );
  }
};
