/**
 * GENERATED by `scripts/gen-paths.mjs` — do not edit.
 *
 * Typed union proof for the file-router prototype.
 */
export const fileEntries = [
  {
    "id": "index",
    "filePath": "/",
    "routePath": "/"
  },
  {
    "id": "api_pkg",
    "filePath": "/api/[pkg]",
    "routePath": "/api/:pkg"
  },
  {
    "id": "docs_chapter",
    "filePath": "/docs/[chapter]",
    "routePath": "/docs/:chapter"
  },
  {
    "id": "search",
    "filePath": "/search",
    "routePath": "/search"
  }
] as const;

export const filePaths = [
  "/",
  "/api/[pkg]",
  "/docs/[chapter]",
  "/search",
] as const;

export const routePaths = [
  "/",
  "/api/:pkg",
  "/docs/:chapter",
  "/search",
] as const;

/** Disk / file-URL templates (`[param]`). */
export type FilePath = "/" | "/api/[pkg]" | "/docs/[chapter]" | "/search";

/** Hyperlink {@link Route} templates (`:param`). */
export type RoutePath = "/" | "/api/:pkg" | "/docs/:chapter" | "/search";

/** Stable route ids derived from those paths. */
export type FileRouteId = "index" | "api_pkg" | "docs_chapter" | "search";

export type FileEntry = (typeof fileEntries)[number];
